christian39: add spanish translations to locale.json
Widdin/DeliBot pull request #27
Opened 2021-06-27 22:51 UTC by christian39

## Changes
* Adds spanish translations to the locale.json

## Additional information
* I intentionally did not translate the  "raids" and "Community Day" since eventhough there is an official translation for those words, people normally uses the English terms. If in the future is required I may create another commit to add those translations.

2021-06-28 20:48 UTC, Widdin requested changes

2021-06-28 20:48 UTC, Widdin commented on delibot/json/locale.json
> +		"ER": "No tienes permiso para ejecutar este comando."
Typo here 😄 
```suggestion
		"ES": "No tienes permiso para ejecutar este comando."
```

2021-06-28 23:55 UTC, christian39 commented on delibot/json/locale.json
> +		"ER": "No tienes permiso para ejecutar este comando."
Fixed!

2021-06-30 21:23 UTC, Widdin approved these changes
Lookin good 👍

2021-06-30 21:28 UTC, merged